name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Read package.json
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{steps.tag.outputs.content}}
        token: ${{ secrets.GITHUB_TOKEN }}
