name: Create Tag

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Autotag
      id: tag
      uses: butlerlogic/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
        strategy: regex
        root: "./VERSION"
        regex_pattern: "/(^[0-9][0-9.]*$)/g"
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{steps.tag.outputs.version}}
        token: ${{ secrets.GITHUB_TOKEN }}
